# Generated by Django 4.2.7 on 2023-11-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_makeaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='makeaccount',
        ),
    ]
