# Generated by Django 4.2.7 on 2023-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_account_login_mypage_remove_makeaccount_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
