# Generated by Django 4.2.7 on 2023-11-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_d_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='d_day',
        ),
    ]
